version: "3.6"

services:
  rexams:
    image: kenjis/rexams:latest
    volumes:
      - type: bind
        source: ./exams
        target: /home/rstudio/exams
      - type: bind
        source: ~/Documents/Sandbox/Problems/macro
        target: /home/rstudio/problems
      - type: bind
        source: ./students.csv
        target: /home/rstudio/students.csv
    ports:
      - 8787:8787
    environment:
      PASSWORD: tomato
